import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "SPARK: Reigniting Learning and Innovation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="main.css" />
      </head>
      <body>
        <nav className="navbar">
          <div className="logo">
            <Link href="/">SPARK</Link>
          </div>
          <ul className="nav-links">
            <li><a href="/sessions">Events & Sessions</a></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
